config/routes.rb
Rails.application.routes.draw do
  resources :active_beers

  resources :beers

  resources :untapped_beers

  resources :locations

end

app/models/active_beer.rb
class ActiveBeer < ActiveRecord::Base
  belongs_to :Location
  belongs_to :Beer
end

app/controllers/active_beers_controller.rb
class ActiveBeersController < ApplicationController
  before_action :set_active_beer, only: [:show, :edit, :update, :destroy]

  # GET /active_beers
  # GET /active_beers.json
  def index
    @active_beers = ActiveBeer.all
  end

  # GET /active_beers/1
  # GET /active_beers/1.json
  def show
  end

  # GET /active_beers/new
  def new
    @active_beer = ActiveBeer.new
  end

  # GET /active_beers/1/edit
  def edit
  end

  # POST /active_beers
  # POST /active_beers.json
  def create
    @active_beer = ActiveBeer.new(active_beer_params)

    respond_to do |format|
      if @active_beer.save
        format.html { redirect_to @active_beer, notice: 'Active beer was successfully created.' }
        format.json { render :show, status: :created, location: @active_beer }
      else
        format.html { render :new }
        format.json { render json: @active_beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /active_beers/1
  # PATCH/PUT /active_beers/1.json
  def update
    respond_to do |format|
      if @active_beer.update(active_beer_params)
        format.html { redirect_to @active_beer, notice: 'Active beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @active_beer }
      else
        format.html { render :edit }
        format.json { render json: @active_beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /active_beers/1
  # DELETE /active_beers/1.json
  def destroy
    @active_beer.destroy
    respond_to do |format|
      format.html { redirect_to active_beers_url, notice: 'Active beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_active_beer
      @active_beer = ActiveBeer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def active_beer_params
      params.require(:active_beer).permit(:Location_id, :Beer_id)
    end
end

app/helpers/active_beers_helper.rb
module ActiveBeersHelper
end

app/views/active_beers/_form.html.erb
<%= form_for(@active_beer) do |f| %>
  <% if @active_beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@active_beer.errors.count, "error") %> prohibited this active_beer from being saved:</h2>

      <ul>
      <% @active_beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Location_id %><br>
    <%= f.text_field :Location_id %>
  </div>
  <div class="field">
    <%= f.label :Beer_id %><br>
    <%= f.text_field :Beer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/active_beers/edit.html.erb
<h1>Editing active_beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @active_beer %> |
<%= link_to 'Back', active_beers_path %>

app/views/active_beers/index.html.erb
<h1>Listing active_beers</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Beer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @active_beers.each do |active_beer| %>
      <tr>
        <td><%= active_beer.Location %></td>
        <td><%= active_beer.Beer %></td>
        <td><%= link_to 'Show', active_beer %></td>
        <td><%= link_to 'Edit', edit_active_beer_path(active_beer) %></td>
        <td><%= link_to 'Destroy', active_beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Active beer', new_active_beer_path %>

app/views/active_beers/new.html.erb
<h1>New active_beer</h1>

<%= render 'form' %>

<%= link_to 'Back', active_beers_path %>

app/views/active_beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @active_beer.Location %>
</p>

<p>
  <strong>Beer:</strong>
  <%= @active_beer.Beer %>
</p>

<%= link_to 'Edit', edit_active_beer_path(@active_beer) %> |
<%= link_to 'Back', active_beers_path %>