config/routes.rb
Rails.application.routes.draw do
  resources :active_beers

  resources :beers

  resources :untapped_beers

  resources :locations

end

app/models/untapped_beer.rb
class UntappedBeer < ActiveRecord::Base
end

app/controllers/untapped_beers_controller.rb
class UntappedBeersController < ApplicationController
  before_action :set_untapped_beer, only: [:show, :edit, :update, :destroy]

  # GET /untapped_beers
  # GET /untapped_beers.json
  def index
    @untapped_beers = UntappedBeer.all
  end

  # GET /untapped_beers/1
  # GET /untapped_beers/1.json
  def show
  end

  # GET /untapped_beers/new
  def new
    @untapped_beer = UntappedBeer.new
  end

  # GET /untapped_beers/1/edit
  def edit
  end

  # POST /untapped_beers
  # POST /untapped_beers.json
  def create
    @untapped_beer = UntappedBeer.new(untapped_beer_params)

    respond_to do |format|
      if @untapped_beer.save
        format.html { redirect_to @untapped_beer, notice: 'Untapped beer was successfully created.' }
        format.json { render :show, status: :created, location: @untapped_beer }
      else
        format.html { render :new }
        format.json { render json: @untapped_beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /untapped_beers/1
  # PATCH/PUT /untapped_beers/1.json
  def update
    respond_to do |format|
      if @untapped_beer.update(untapped_beer_params)
        format.html { redirect_to @untapped_beer, notice: 'Untapped beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @untapped_beer }
      else
        format.html { render :edit }
        format.json { render json: @untapped_beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /untapped_beers/1
  # DELETE /untapped_beers/1.json
  def destroy
    @untapped_beer.destroy
    respond_to do |format|
      format.html { redirect_to untapped_beers_url, notice: 'Untapped beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_untapped_beer
      @untapped_beer = UntappedBeer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def untapped_beer_params
      params.require(:untapped_beer).permit(:beer_style, :rating_score, :description, :untapped_id, :updated)
    end
end

app/helpers/untapped_beers_helper.rb
module UntappedBeersHelper
end

app/views/untapped_beers/_form.html.erb
<%= form_for(@untapped_beer) do |f| %>
  <% if @untapped_beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@untapped_beer.errors.count, "error") %> prohibited this untapped_beer from being saved:</h2>

      <ul>
      <% @untapped_beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :beer_style %><br>
    <%= f.text_field :beer_style %>
  </div>
  <div class="field">
    <%= f.label :rating_score %><br>
    <%= f.text_field :rating_score %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :untapped_id %><br>
    <%= f.number_field :untapped_id %>
  </div>
  <div class="field">
    <%= f.label :updated %><br>
    <%= f.date_select :updated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/untapped_beers/edit.html.erb
<h1>Editing untapped_beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @untapped_beer %> |
<%= link_to 'Back', untapped_beers_path %>

app/views/untapped_beers/index.html.erb
<h1>Listing untapped_beers</h1>

<table>
  <thead>
    <tr>
      <th>Beer style</th>
      <th>Rating score</th>
      <th>Description</th>
      <th>Untapped</th>
      <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @untapped_beers.each do |untapped_beer| %>
      <tr>
        <td><%= untapped_beer.beer_style %></td>
        <td><%= untapped_beer.rating_score %></td>
        <td><%= untapped_beer.description %></td>
        <td><%= untapped_beer.untapped_id %></td>
        <td><%= untapped_beer.updated %></td>
        <td><%= link_to 'Show', untapped_beer %></td>
        <td><%= link_to 'Edit', edit_untapped_beer_path(untapped_beer) %></td>
        <td><%= link_to 'Destroy', untapped_beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Untapped beer', new_untapped_beer_path %>

app/views/untapped_beers/new.html.erb
<h1>New untapped_beer</h1>

<%= render 'form' %>

<%= link_to 'Back', untapped_beers_path %>

app/views/untapped_beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Beer style:</strong>
  <%= @untapped_beer.beer_style %>
</p>

<p>
  <strong>Rating score:</strong>
  <%= @untapped_beer.rating_score %>
</p>

<p>
  <strong>Description:</strong>
  <%= @untapped_beer.description %>
</p>

<p>
  <strong>Untapped:</strong>
  <%= @untapped_beer.untapped_id %>
</p>

<p>
  <strong>Updated:</strong>
  <%= @untapped_beer.updated %>
</p>

<%= link_to 'Edit', edit_untapped_beer_path(@untapped_beer) %> |
<%= link_to 'Back', untapped_beers_path %>